CREATE TYPE role AS ENUM ('admin', 'user');

CREATE TABLE users
(
    id       VARCHAR(20) PRIMARY KEY,
    name     VARCHAR(20) NOT NULL UNIQUE,
    naver_id VARCHAR(255) NOT NULL UNIQUE,
    role     role         NOT NULL DEFAULT 'user'
);

CREATE TABLE articles
(
    id           INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title        VARCHAR(255) NOT NULL DEFAULT '',
    content      TEXT         NOT NULL DEFAULT '',
    author_id    VARCHAR(20) NOT NULL REFERENCES users (id) ON UPDATE CASCADE,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP
);

CREATE TABLE comments
(
    id         INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content    VARCHAR(1024) NOT NULL,
    author_id  VARCHAR(20)  NOT NULL REFERENCES users (id) ON UPDATE CASCADE,
    article_id INT           NOT NULL REFERENCES articles (id) ON DELETE CASCADE,
    created_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE views
(
    id         INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    article_id INT       NOT NULL REFERENCES articles (id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE likes
(
    article_id INT          NOT NULL REFERENCES articles (id) ON DELETE CASCADE,
    user_id    VARCHAR(20) NOT NULL REFERENCES users (id) ON UPDATE CASCADE,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (article_id, user_id)
);

CREATE TABLE files
(
    id         INT          PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    article_id INT          NOT NULL REFERENCES articles (id) ON DELETE CASCADE,
    name       VARCHAR(20) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (article_id, name)
);
