services:
  next:
    build:
      context: .
      args:
        NEXT_PUBLIC_NAVER_ID: ${NEXT_PUBLIC_NAVER_ID}
        NEXT_PUBLIC_THUMBNAIL_URL: ${NEXT_PUBLIC_THUMBNAIL_URL}
    env_file: .env
    environment:
      DATABASE_URL: postgres://blog:${DB_PASSWORD}@db/blog
      REDIS_URL: redis://redis
      PORT: 3000
      UPLOAD_DIR: /var/uploads
    restart: always
    ports:
      - ${PORT}:3000
    volumes:
      - ${UPLOAD_DIR}:/var/uploads:Z
  db:
    image: docker.io/library/postgres:16.0-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: blog
      POSTGRES_DB: blog
    volumes:
      - ${DB_DATA}:/var/lib/postgresql/data:Z
    ports:
      - "127.0.0.1:5432:5432"
    command: ["postgres", "-c", "listen_addresses=*"]
    restart: always
  redis:
    image: docker.io/library/redis:7.2.1-alpine
    restart: always
