extern crate napi_build;

// generated by `sqlx migrate build-script`
fn main() {
  // trigger recompilation when a new migration is added
  println!("cargo:rerun-if-changed=migrations");
  napi_build::setup();
}
