/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ArticleSummary {
  id: number
  title: string
  publishedAt: string
  author: Author
  commentsCount: number
  likesCount: number
  viewsCount: number
}
export interface Author {
  id: string
  name: string
}
export interface Article {
  id: number
  title: string
  content: string
  publishedAt: string
  author: Author
  likesCount: number
  viewsCount: number
  comments: Array<Comment>
  next?: ArticleSummary
  prev?: ArticleSummary
}
export interface Comment {
  id: number
  content: string
  createdAt: string
  author: Author
}
export class QueryEngine {
  static new(databaseUrl: string): QueryEngine
  listArticles(): Promise<Array<ArticleSummary>>
  listPopularArticles(): Promise<Array<ArticleSummary>>
  getArticle(id: number): Promise<Article | null>
}
