/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ArticleSummary {
  id: number
  title: string
  publishedAt: string
  author: Author
  commentsCount: number
  likesCount: number
  viewsCount: number
}
export interface Author {
  id: string
  name: string
}
export interface Article {
  id: number
  title: string
  content: string
  publishedAt: string
  author: Author
  likesCount: number
  viewsCount: number
  comments: Array<Comment>
  next?: ArticleSummary
  prev?: ArticleSummary
}
export interface Comment {
  id: number
  content: string
  createdAt: string
  author: Author
}
export const enum Role {
  Admin = 'Admin',
  User = 'User'
}
export interface User {
  id: string
  name: string
  role: Role
}
export const enum UserConflict {
  NaverId = 'NaverId',
  UserId = 'UserId',
  Name = 'Name'
}
export class QueryEngine {
  static new(databaseUrl: string): QueryEngine
  listArticles(): Promise<Array<ArticleSummary>>
  listPopularArticles(): Promise<Array<ArticleSummary>>
  getArticle(id: number): Promise<Article | null>
  getUserByNaverId(naverId: string): Promise<User | null>
  getUserById(userId: string): Promise<User | null>
  createUser(naverId: string, userId: string, userName: string): Promise<UserConflict | null>
}
