// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.pgmigrations */
export type PgmigrationsId = number & { __brand?: 'PgmigrationsId' };

/** Represents the table public.pgmigrations */
export default interface PgmigrationsTable {
  id: ColumnType<PgmigrationsId, PgmigrationsId | undefined, PgmigrationsId>;

  name: ColumnType<string, string, string>;

  run_on: ColumnType<string, string, string>;
}

export type Pgmigrations = Selectable<PgmigrationsTable>;

export type NewPgmigrations = Insertable<PgmigrationsTable>;

export type PgmigrationsUpdate = Updateable<PgmigrationsTable>;
