// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.role */
enum Role {
  admin = 'admin',
  user = 'user',
};

export default Role;
